### PR TITLE
Manage TypeScript declaration files using npm

### PR DESCRIPTION
**Pull request by od1k**
TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

TypeScript 2 made it easier to [install declaration files using npm](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/). 

Moving all the declaration file dependencies from typings to npm solves the problem where you have to install all the definitions manually (issue #124).

Now you just have to `npm install apollo-server` into your TS project and it just works, except for graphql definitions, those still need to be installed using the typings utility. Couldn't get them to work by installing from npm, for some reason.

**Note:** Running `npm install` in an existing project will probably case duplicate definition errors with the typings directory. To resolve that just delete the typings directory and run `typings install` to install the graphql definitions.

Also, having `@types/chai` in *devDependencies* resulted in missing type definition when compiling project that is depending on apollo-server. Thats why it's in *dependencies* section.

### CODE REVIEW

**Comment by helfer** [comment]
@od1k cool! I think there's even a typed-graphql npm package that we could use (same content as the github repo), which would make the `typings install` step completely unnecessary. We used it in graphql-tools.

**Comment by od1k** [comment]
For some reason, when typed-graphql was installed from npm, the compiler was complaining about missing types. But I will take another look at this problem in the evening. Completely getting rid of 'typings install' would be really nice.

**Comment by DxCx** [comment]
@od1k to use typed-graphql package you just need to state it in tsconfig.
[example](https://github.com/apollostack/graphql-tools/blob/master/tsconfig.json#L21)

**Comment by od1k** [comment]
Thanks @DxCx!
I've tried your suggestion but run into a couple of problems.
It seems that having `types` inside `compilerOptions` disables automatic searching of types. At least something breaks, because I had to add `mocha` to the list as well to get it to compile.

But even when I got it working there was still one issue remaining. When you `npm install apollo-server` into a project it does not compile because of all the graphql types missing.

The only way I could get it to work without having to do any additional steps after `npm install` is by having a new file `typings.d.ts` with `/// <reference types="typed-graphql" />`, just as the typed-graphql GitHub readme states.
While this does work, it feels like a hack and I'm not sure if I should push those changes.

Ideal scenario would be for typed-graphql to be published to npm @types.

**Comment by DxCx** [comment]
ok @od1k cool.
so please note this PR (DefinitelyTyped/DefinitelyTyped#11598)
which will give you @types/graphql package.

**Comment by od1k** [comment]
Nice! I guess we wait until it becomes available on npm.

**Comment by DxCx** [comment]
@od1k i think it might take some time, IMO using the typings file can work in the meanwhile..
especially when in that point we do prefere to work against typed-graphql until we know that the new @types can be trusted.

**Comment by od1k** [comment]
I guess you're right. I didn't find any information on how long does it take to get merged PRs on definitelytyped to get published to npm, so I've stayed with solution mentioned above.

I think this is ready to be merged.

**Pull request merged**
