### PR TITLE
Add failing test for file upload

### PR DESCRIPTION
**Pull request by HriBB**
OK I hope I did it right this time.

I only added a failing test for file upload. @helfer let me know if it is OK ;)

TODO:

- [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
Awesome, merged!

**Comment by HriBB** [comment]
@helfer great! So what's next?

I already have a working file upload implementation for koa using [`async-busboy`](https://github.com/m4nuC/async-busboy), which uses raw http request. I could create `fileUpload()` module, which we can use in all integrations. Anyway, let me know how to proceed ;)

**Comment by helfer** [comment]
Yeah, if you could make a module that can be used by all integrations, that would be great in theory, but in practice each server uses a different way to handle file uploads. HAPI has it built-in, I believe, while with Express you have to parse the request yourself using the appropriate module.

Because each server handles it differently, we decided not to handle the request parsing in apollo server. If possible, we should keep it that way for file uploads as well. So instead of adding a new dependency, you should see if you can get the tests to pass. For express, I think it would be enough to provide the right arguments to body parser. If that works for Koa and HAPI as well, then we don't actually need to make any modifications to apollo-server's core or integrations. Then all you have to do is to set up the right request parsing for each server so they can pass the test. If it's not possible to have a common setup for all of them, then maybe we need to split out the file upload test and do it separately for each integration.

Do you think that makes sense?

@nnance Do you know how file uploading works in HAPI? Would it be easy to get the current file upload test to pass without major modifications to how we set up the tests for each server?

**Comment by HriBB** [comment]
I think I understand what you mean. I am no expert in this field, but I believe it should be possible with the right body parser, at least for express and koa. Maybe we can extract the logic into a custom middleware? Then users could do something like `app.use(koaApolloUpload(options))`.

 I will play with this when I find some spare time. It's cool, because I am currently working on two different apps and one uses `apolloExpress` and the other one `apolloKoa` :)

**Comment by helfer** [comment]
Haha, nice! I think the main thing we have to do is figure out how to make it work. If it's simple enough (i.e. just a few lines of code), then I think we shouldn't write a middleware for it, because that will a) limit what people can do and b) require us to keep it up to date, which doesn't seem worth it given the minimal thing it adds.

**Pull request merged**
