### PR TITLE
Pass ctx instead of ctx.request to koa options function

### PR DESCRIPTION
**Pull request by HriBB**
This is a breaking change. We need to mention this in the changelog.

TODO:

- [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
@HriBB can you add that to the changelog? I think it's a good change, but it's a pretty major breaking change for the Koa integration.

**Comment by HriBB** [comment]
Done!

**Comment by mikeifomin** [comment]
@HriBB 
I think you forgot to fix an interface for `KoaApolloOptionsFunction`?

**Comment by HriBB** [comment]
@mikeifomin you're right, thanks! @helfer should I add a test for that?

**Comment by helfer** [comment]
@HriBB I don't even know how we could test for missing (type) exports. If you figure out a way to do that, I definitely want to know!

**Comment by HriBB** [comment]
Should be fixed now, @mikeifomin can you check? @helfer yeah I'm not very experienced with tests. I proposed that because I ran tests after fixing the `ctx` and all tests passed, so I assumed my change was OK.

**Comment by helfer** [comment]
@HriBB @mikeifomin is this ready to merge?

**Comment by HriBB** [comment]
@helfer yes!

**Comment by stubailo** [comment]
So how do we release this? Bump to v0.4?

**Comment by helfer** [comment]
@stubailo yeah, we could release this before the monorepo, which would then be version 0.5

**Comment by stubailo** [comment]
OK, will do.

**Pull request merged**
