### PR TITLE
Fix query batching for single queries for hapi integration.

### PR DESCRIPTION
**Pull request by dahjelle**
The hapi integration didn't correctly check to see if a query was batched or not.

TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
Thanks!

**Comment by dahjelle** [comment]
Any ETA for getting this published? I completely understand if you are waiting for other changes—just helps me know if I should temporarily deploy from `master` or if a new NPM package is coming out soon. Thanks for all your work! :-D

**Comment by nnance** [comment]
@helfer @dahjelle I am actively refactoring the HAPI integration.  I will make sure to resolved this issue in my new version and will reference this issue in my PR for review.  ETA tomorrow 9/7

**Comment by nnance** [comment]
@dahjelle I have opened the PR and welcome your feedback. #127

**Pull request merged**
