### PR TITLE
fix passHeader for Hapi

### PR DESCRIPTION
**Pull request by creatorkuang**
TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by nnance** [comment]
@creatorkuang this looks good, just one ask. Can you add the same fix to Koa?

**Comment by stubailo** [comment]
Hi, any news on this? Also, I fixed the tests on `master`, can you rebase on that?

**Comment by creatorkuang** [comment]
@nnance I will try to fix the Koa. @stubailo Ok, i'll try.

**Comment by stubailo** [comment]
@creatorkuang you have some missing trailing commas causing a lint error which makes the test CI fail.

**Comment by stubailo** [comment]
Merged: aadef1f874b703d6f45ad2ab9eda7ed27b0d1a10

**Pull request closed without merging**
