### PR TITLE
Expose OperationStore

### PR DESCRIPTION
**Pull request by nnance**
TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
Looks great!

**Comment by tonyxiao** [comment]
What exactly is the operationStore? Can't find any docs on it cc @helfer

**Comment by tonyxiao** [comment]
Is it related to persisted queries at all?

**Comment by helfer** [comment]
@tonyxiao Yes, the operationStore is the thing that contains the persisted queries. The tests are the best docs we have so far: https://github.com/apollostack/apollo-server/blob/master/src/modules/operationStore.test.ts

If you find it useful, and would be willing to make a PR to add it to the docs, let me know!

**Pull request merged**
